/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import javax.swing.JFrame;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Mahe
 */
public class User_Feedback extends javax.swing.JFrame {
    
static String user;
Connection conn=null;
    OraclePreparedStatement pst=null;
    OracleResultSet rs=null;
    /**
     * 
     * Creates new form User_Feedback
     */
    public User_Feedback() {
        
        initComponents();
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        f = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sp = new javax.swing.JCheckBox();
        mark = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        uig = new javax.swing.JRadioButton();
        uia = new javax.swing.JRadioButton();
        uib = new javax.swing.JRadioButton();
        dg = new javax.swing.JRadioButton();
        da = new javax.swing.JRadioButton();
        db = new javax.swing.JRadioButton();
        eg = new javax.swing.JRadioButton();
        ea = new javax.swing.JRadioButton();
        eb = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(740, 560));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Feedback Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please tell us how we can improve our services");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(50000, 50000));

        f.setColumns(20);
        f.setRows(5);
        jScrollPane1.setViewportView(f);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 266, 135));

        jButton1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 365, 134, 36));

        jButton2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton2.setText("Logout");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 434, 134, 37));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("(max 100 words)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        sp.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(sp);
        sp.setForeground(new java.awt.Color(255, 255, 255));
        sp.setText("Survey Participant");
        getContentPane().add(sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 132, -1, -1));

        mark.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(mark);
        mark.setForeground(new java.awt.Color(255, 255, 255));
        mark.setText("Marketer");
        getContentPane().add(mark, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 132, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Accesed as");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 136, -1, -1));

        uig.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(uig);
        getContentPane().add(uig, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 204, -1, -1));

        uia.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(uia);
        getContentPane().add(uia, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 204, -1, -1));

        uib.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(uib);
        getContentPane().add(uib, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 204, -1, -1));

        dg.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup3.add(dg);
        getContentPane().add(dg, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 246, -1, -1));

        da.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup3.add(da);
        getContentPane().add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 246, -1, -1));

        db.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup3.add(db);
        getContentPane().add(db, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 246, -1, -1));

        eg.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup4.add(eg);
        getContentPane().add(eg, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 285, -1, -1));

        ea.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup4.add(ea);
        getContentPane().add(ea, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 285, -1, -1));

        eb.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup4.add(eb);
        getContentPane().add(eb, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 285, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Good");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 173, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Acceptable");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 173, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Below Average");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 173, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("User Interface");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Relevance of Data");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Overall Experiece");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, 23));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Home h=new Home();
h.setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String access = " ",rate1=" ", rate2=" ", rate3=" ";
if(sp.isSelected())
    access="Survey User";
else if(mark.isSelected())
    access="Marketer";
 if(uig.isSelected())
     rate1="Good";
 else if(uia.isSelected())
     rate1="Average";
 else if(uib.isSelected())
     rate1="Below Average";
 if(dg.isSelected())
     rate2="Good";
 else if(da.isSelected())
     rate2="Average";
 else if(db.isSelected())
     rate2="Below Average";
 if(eg.isSelected())
     rate3="Good";
 else if(ea.isSelected())
     rate3="Average";
 else if(eb.isSelected())
     rate3="Below Average";
        conn=SqlConnect.ConnDB();
    try
{
   String sql="insert into feedback values(?,?,?,?,?)";
    pst=(OraclePreparedStatement) conn.prepareStatement(sql);
    pst.setString(1,access);
    pst.setString(2,rate1); 
    pst.setString(3,rate2); 
    pst.setString(4,rate3); 
    pst.setString(5,f.getText()); 
rs=(OracleResultSet) pst.executeQuery();
    
    if(rs.next())
    {
        
        JOptionPane.showMessageDialog(null,"Thank You for your Feedback. Please Logout to exit");      
    }
    else
    {
        JOptionPane.showMessageDialog(null,"try again");
    }
    conn.close();   
                
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null,"Word Limit exceeded. Try again");
}       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JRadioButton da;
    private javax.swing.JRadioButton db;
    private javax.swing.JRadioButton dg;
    private javax.swing.JRadioButton ea;
    private javax.swing.JRadioButton eb;
    private javax.swing.JRadioButton eg;
    private javax.swing.JTextArea f;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox mark;
    private javax.swing.JCheckBox sp;
    private javax.swing.JRadioButton uia;
    private javax.swing.JRadioButton uib;
    private javax.swing.JRadioButton uig;
    // End of variables declaration//GEN-END:variables
}
